CREATE TABLE IF NOT EXISTS area (
  ID_AREA integer NOT NULL,
  AREA varchar(100)  NOT NULL,
  PRIMARY KEY (ID_AREA)
)  ;

CREATE TABLE IF NOT EXISTS atributo (
  ID_ATRIBUTO integer NOT NULL,
  NOME varchar(100) NOT NULL,
  NOMEPLURAL varchar(100) NOT NULL,
  GENERO tinyint(4) NOT NULL,
  CARDINALIDADE int(6) NOT NULL,
  ID_ATRIBUTOSINONIMO integer DEFAULT NULL,
  PRIMARY KEY (ID_ATRIBUTO)
) ;

CREATE TABLE IF NOT EXISTS complemento (
  ID_VALOR integer NOT NULL,
  COMPLEMENTO varchar(255) DEFAULT NULL
) ;

CREATE TABLE IF NOT EXISTS disciplina (
  ID_DISCIPLINA integer NOT NULL,
  DISCIPLINA varchar(100) NOT NULL,
  SIGLA varchar(15) DEFAULT NULL,
  HABILITADA bit(1) NOT NULL,
  PRIMARY KEY (ID_DISCIPLINA)
) ;


CREATE TABLE IF NOT EXISTS objeto (
  ID_OBJETO integer NOT NULL,
  NOME varchar(100) NOT NULL,
  NOMEPLURAL varchar(100) NOT NULL,
  DATA_OBJETO date NOT NULL,
  ID_USUARIO integer NOT NULL,
  TIPO integer DEFAULT NULL,
  ID_SUPEROBJETO integer DEFAULT NULL,
  PRIMARY KEY (ID_OBJETO)
) ;

CREATE TABLE IF NOT EXISTS objeto_disciplina (
  ID integer NOT NULL,
  ID_OBJETO integer NOT NULL,
  ID_DISCIPLINA integer NOT NULL,
  PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS objeto_subarea (
  ID_OBJETO integer NOT NULL,
  ID_SUBAREA integer NOT NULL
)  ;

CREATE TABLE IF NOT EXISTS orav (
  ID_ORAV integer NOT NULL,
  ID_OBJETO integer NOT NULL,
  ID_ATRIBUTO integer NOT NULL,
  ID_VALOR integer NOT NULL,
  DATA_ORAV date NOT NULL,
  PRIMARY KEY (ID_ORAV)
) ;

CREATE TABLE IF NOT EXISTS propriedade (
  ID_PROPRIEDADE integer NOT NULL,
  PROPRIEDADE varchar(127) DEFAULT NULL,
  GENERO tinyint(4) DEFAULT NULL,
  PRIMARY KEY (ID_PROPRIEDADE)
) ;

CREATE TABLE IF NOT EXISTS qualificador (
  ID_QUALIFICADOR integer NOT NULL,
  QUALIFICADOR varchar(100)  NOT NULL,
  PRIMARY KEY (ID_QUALIFICADOR)
)  ;

CREATE TABLE IF NOT EXISTS subarea (
  ID_SUBAREA integer NOT NULL,
  COD_CNPQ varchar(12)  NOT NULL,
  SUBAREA char(100) CHARACTER SET cp850 COLLATE cp850_bin NOT NULL,
  ID_AREA integer NOT NULL,
  PRIMARY KEY (ID_SUBAREA)
)  ;

CREATE TABLE IF NOT EXISTS valor (
  ID_VALOR integer NOT NULL,
  NOME varchar(512) DEFAULT NULL,
  NOME_FONEMA text,
  AUTOR varchar(255) DEFAULT NULL,
  AUTOR_FONEMA varchar(255) DEFAULT NULL,
  ANO integer DEFAULT NULL,
  DATA_EVENTO date DEFAULT NULL,
  ID_OBJETO integer DEFAULT NULL,
  PRIMARY KEY (ID_VALOR)
) ;

CREATE TABLE IF NOT EXISTS valor_propriedade (
  ID_VALOR integer NOT NULL,
  ID_PROPRIEDADE integer NOT NULL,
  PRIMARY KEY (ID_VALOR,ID_PROPRIEDADE)
) ;

CREATE TABLE IF NOT EXISTS valor_qualificador (
  ID_VALOR integer NOT NULL,
  ID_QUALIFICADOR integer NOT NULL,
  PRIMARY KEY (ID_VALOR,ID_QUALIFICADOR)
)  ;

ALTER TABLE complemento
  ADD CONSTRAINT fk_complemento1 FOREIGN KEY (ID_VALOR) REFERENCES valor (ID_VALOR) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE objeto
  ADD CONSTRAINT fk_objeto1 FOREIGN KEY (ID_SUPEROBJETO) REFERENCES objeto (ID_OBJETO);

ALTER TABLE objeto_disciplina
  ADD CONSTRAINT fk_objeto_disciplina1 FOREIGN KEY (ID_OBJETO) REFERENCES objeto (ID_OBJETO),
  ADD CONSTRAINT fk_objeto_disciplina2 FOREIGN KEY (ID_DISCIPLINA) REFERENCES disciplina (ID_DISCIPLINA);

ALTER TABLE objeto_subarea
  ADD CONSTRAINT fk_objeto_subarea1 FOREIGN KEY (ID_OBJETO) REFERENCES objeto (ID_OBJETO),
  ADD CONSTRAINT fk_objeto_subarea2 FOREIGN KEY (ID_SUBAREA) REFERENCES subarea (ID_SUBAREA);

ALTER TABLE orav
  ADD CONSTRAINT fk_orav1 FOREIGN KEY (ID_OBJETO) REFERENCES objeto (ID_OBJETO),
  ADD CONSTRAINT fk_orav2 FOREIGN KEY (ID_ATRIBUTO) REFERENCES atributo (ID_ATRIBUTO),
  ADD CONSTRAINT fk_orav3 FOREIGN KEY (ID_VALOR) REFERENCES valor (ID_VALOR);

ALTER TABLE subarea
  ADD CONSTRAINT fk_subarea1 FOREIGN KEY (ID_AREA) REFERENCES area (ID_AREA);

ALTER TABLE valor
  ADD CONSTRAINT fk_valor1 FOREIGN KEY (ID_OBJETO) REFERENCES objeto (ID_OBJETO);

ALTER TABLE valor_propriedade
  ADD CONSTRAINT fk_valor_propriedade1 FOREIGN KEY (ID_VALOR) REFERENCES valor (ID_VALOR),
  ADD CONSTRAINT fk_valor_propriedade2 FOREIGN KEY (ID_PROPRIEDADE) REFERENCES propriedade (ID_PROPRIEDADE);

ALTER TABLE valor_qualificador
  ADD CONSTRAINT fk_valor_qualificador1 FOREIGN KEY (ID_VALOR) REFERENCES valor (ID_VALOR),
  ADD CONSTRAINT fk_valor_qualificador2 FOREIGN KEY (ID_QUALIFICADOR) REFERENCES qualificador (ID_QUALIFICADOR);