SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `area` (
  `ID_AREA` int(11) NOT NULL,
  `AREA` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID_AREA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

CREATE TABLE IF NOT EXISTS `atributo` (
  `ID_ATRIBUTO` int(11) NOT NULL,
  `NOME` varchar(100) NOT NULL,
  `NOMEPLURAL` varchar(100) NOT NULL,
  `GENERO` tinyint(4) NOT NULL,
  `CARDINALIDADE` int(6) NOT NULL,
  `ID_ATRIBUTOSINONIMO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_ATRIBUTO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `complemento` (
  `ID_VALOR` int(11) NOT NULL,
  `COMPLEMENTO` varchar(255) DEFAULT NULL,
  KEY `fk_complemento1` (`ID_VALOR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `disciplina` (
  `ID_DISCIPLINA` int(11) NOT NULL,
  `DISCIPLINA` varchar(100) NOT NULL,
  `SIGLA` varchar(15) DEFAULT NULL,
  `HABILITADA` bit(1) NOT NULL,
  PRIMARY KEY (`ID_DISCIPLINA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `objeto` (
  `ID_OBJETO` int(11) NOT NULL,
  `NOME` varchar(100) NOT NULL,
  `NOMEPLURAL` varchar(100) NOT NULL,
  `DATA_OBJETO` date NOT NULL,
  `ID_USUARIO` int(11) NOT NULL,
  `TIPO` int(11) DEFAULT NULL,
  `ID_SUPEROBJETO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_OBJETO`),
  KEY `fk_objeto1` (`ID_SUPEROBJETO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `objeto_disciplina` (
  `ID` int(11) NOT NULL,
  `ID_OBJETO` int(11) NOT NULL,
  `ID_DISCIPLINA` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_objeto_disciplina1` (`ID_OBJETO`),
  KEY `fk_objeto_disciplina2` (`ID_DISCIPLINA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `objeto_subarea` (
  `ID_OBJETO` int(11) NOT NULL,
  `ID_SUBAREA` int(11) NOT NULL,
  KEY `fk_objeto_subarea1` (`ID_OBJETO`),
  KEY `fk_objeto_subarea2` (`ID_SUBAREA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

CREATE TABLE IF NOT EXISTS `orav` (
  `ID_ORAV` int(11) NOT NULL,
  `ID_OBJETO` int(11) NOT NULL,
  `ID_ATRIBUTO` int(11) NOT NULL,
  `ID_VALOR` int(11) NOT NULL,
  `DATA_ORAV` date NOT NULL,
  PRIMARY KEY (`ID_ORAV`),
  KEY `fk_orav1` (`ID_OBJETO`),
  KEY `fk_orav2` (`ID_ATRIBUTO`),
  KEY `fk_orav3` (`ID_VALOR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `propriedade` (
  `ID_PROPRIEDADE` int(11) NOT NULL,
  `PROPRIEDADE` varchar(127) DEFAULT NULL,
  `GENERO` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID_PROPRIEDADE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `qualificador` (
  `ID_QUALIFICADOR` int(11) NOT NULL,
  `QUALIFICADOR` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID_QUALIFICADOR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

CREATE TABLE IF NOT EXISTS `subarea` (
  `ID_SUBAREA` int(11) NOT NULL,
  `COD_CNPQ` varchar(12) COLLATE latin1_bin NOT NULL,
  `SUBAREA` char(100) CHARACTER SET cp850 COLLATE cp850_bin NOT NULL,
  `ID_AREA` int(11) NOT NULL,
  PRIMARY KEY (`ID_SUBAREA`),
  KEY `fk_subarea1` (`ID_AREA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

CREATE TABLE IF NOT EXISTS `valor` (
  `ID_VALOR` int(11) NOT NULL,
  `NOME` varchar(512) DEFAULT NULL,
  `NOME_FONEMA` text,
  `AUTOR` varchar(255) DEFAULT NULL,
  `AUTOR_FONEMA` varchar(255) DEFAULT NULL,
  `ANO` int(11) DEFAULT NULL,
  `DATA_EVENTO` date DEFAULT NULL,
  `ID_OBJETO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_VALOR`),
  KEY `fk_valor1` (`ID_OBJETO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `valor_propriedade` (
  `ID_VALOR` int(11) NOT NULL,
  `ID_PROPRIEDADE` int(11) NOT NULL,
  PRIMARY KEY (`ID_VALOR`,`ID_PROPRIEDADE`),
  KEY `fk_valor_propriedade2` (`ID_PROPRIEDADE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `valor_qualificador` (
  `ID_VALOR` int(11) NOT NULL,
  `ID_QUALIFICADOR` int(11) NOT NULL,
  PRIMARY KEY (`ID_VALOR`,`ID_QUALIFICADOR`),
  KEY `fk_valor_qualificador2` (`ID_QUALIFICADOR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

CREATE TABLE IF NOT EXISTS `unknown` (
  `ID_UNKNOWN` int(11) NOT NULL,
  `OBS` varchar(255) NOT NULL,
  PRIMARY KEY (`ID_UNKNOWN`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

ALTER TABLE `complemento`
  ADD CONSTRAINT `fk_complemento1` FOREIGN KEY (`ID_VALOR`) REFERENCES `valor` (`ID_VALOR`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `objeto`
  ADD CONSTRAINT `fk_objeto1` FOREIGN KEY (`ID_SUPEROBJETO`) REFERENCES `objeto` (`ID_OBJETO`);

ALTER TABLE `objeto_disciplina`
  ADD CONSTRAINT `fk_objeto_disciplina1` FOREIGN KEY (`ID_OBJETO`) REFERENCES `objeto` (`ID_OBJETO`),
  ADD CONSTRAINT `fk_objeto_disciplina2` FOREIGN KEY (`ID_DISCIPLINA`) REFERENCES `disciplina` (`ID_DISCIPLINA`);

ALTER TABLE `objeto_subarea`
  ADD CONSTRAINT `fk_objeto_subarea1` FOREIGN KEY (`ID_OBJETO`) REFERENCES `objeto` (`ID_OBJETO`),
  ADD CONSTRAINT `fk_objeto_subarea2` FOREIGN KEY (`ID_SUBAREA`) REFERENCES `subarea` (`ID_SUBAREA`);

ALTER TABLE `orav`
  ADD CONSTRAINT `fk_orav1` FOREIGN KEY (`ID_OBJETO`) REFERENCES `objeto` (`ID_OBJETO`),
  ADD CONSTRAINT `fk_orav2` FOREIGN KEY (`ID_ATRIBUTO`) REFERENCES `atributo` (`ID_ATRIBUTO`),
  ADD CONSTRAINT `fk_orav3` FOREIGN KEY (`ID_VALOR`) REFERENCES `valor` (`ID_VALOR`);

ALTER TABLE `subarea`
  ADD CONSTRAINT `fk_subarea1` FOREIGN KEY (`ID_AREA`) REFERENCES `area` (`ID_AREA`);

ALTER TABLE `valor`
  ADD CONSTRAINT `fk_valor1` FOREIGN KEY (`ID_OBJETO`) REFERENCES `objeto` (`ID_OBJETO`);

ALTER TABLE `valor_propriedade`
  ADD CONSTRAINT `fk_valor_propriedade1` FOREIGN KEY (`ID_VALOR`) REFERENCES `valor` (`ID_VALOR`),
  ADD CONSTRAINT `fk_valor_propriedade2` FOREIGN KEY (`ID_PROPRIEDADE`) REFERENCES `propriedade` (`ID_PROPRIEDADE`);

ALTER TABLE `valor_qualificador`
  ADD CONSTRAINT `fk_valor_qualificador1` FOREIGN KEY (`ID_VALOR`) REFERENCES `valor` (`ID_VALOR`),
  ADD CONSTRAINT `fk_valor_qualificador2` FOREIGN KEY (`ID_QUALIFICADOR`) REFERENCES `qualificador` (`ID_QUALIFICADOR`);